# Supported funding platforms

github: [shreyashpatel5506]

# Optional platforms (add later if you create accounts)
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:

# Custom sponsorship links
custom:
  - https://github.com/shreyashpatel5506/gitprofileAi
